### PR TITLE
fixing a missing index

### PR DESCRIPTION
**Pull request by tohidemyname**
fix missing index and newlines in cleanup regexes

### CODE REVIEW

**Comment by yulian-gaponenko** [comment]
Hi @tohidemyname ,
Thank you for your contribution!

Would you mind signing the Contributor License Agreement?
The details are available at https://itextpdf.com/en/how-buy/legal/itext-contributor-license-agreement
We need it in order to be able to merge your PR

---

On a separate note, could you please provide some information on the issue you are fixing with this PR? You could describe it here or simply add a test case in the PR itself.

**Comment by tohidemyname** [comment]
@yulian-gaponenko Thanks for the introduction. I have filed and emailed my agreement. Please let me know if you need more materials.

**Comment by yulian-gaponenko** [comment]
Hi @tohidemyname 
I'm afraid we can't find your email. Have you sent it to the `dev.intern@itextpdf.com` ?

**Comment by vitali-pr** [comment]
Hi @tohidemyname 
After deeper investigation it appears that the fix is not correct or not full. We intentionally don't put word and line separators (spaces and line endings) into indexMap not to assign them to any of the content found in the document. Your fix breaks the behavior and quite some automated tests.

It feels like you have an issue (exception?) on some particular content and a regexp. But looking at our code I can't see where the problem can occur.

Could you, please add a sample showing what your fix is supposed to fix exactly and we will come up with a solution.

**Comment by vitali-pr** [comment]
I'm closing this PR. We will reopen it after getting more info from @tohidemyname .

**Pull request closed without merging**
